# Generated by Django 4.2.9 on 2024-11-04 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0002_alter_group_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('file_type', models.SmallIntegerField(choices=[(1, 'Proposal'), (2, 'Pre-Defence'), (3, 'Defence')])),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='comments',
            field=models.ManyToManyField(related_name='group_comments', to='Users.comment'),
        ),
        migrations.AddField(
            model_name='group',
            name='files',
            field=models.ManyToManyField(related_name='group_files', to='Users.files'),
        ),
    ]
