# Generated by Django 4.2.9 on 2024-11-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_files_comment_group_comments_group_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='url',
        ),
        migrations.AddField(
            model_name='files',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
