# Generated by Django 4.2.9 on 2024-11-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_remove_files_url_files_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
