# Generated by Django 4.2.9 on 2024-11-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_files_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='obtained_marks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
