# Generated by Django 4.2.9 on 2024-11-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_student_obtained_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(related_name='member_students', to='Users.student'),
        ),
    ]
