# Generated by Django 4.2.9 on 2024-11-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_group_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='comments',
            field=models.ManyToManyField(default=list, related_name='group_comments', to='Users.comment'),
        ),
        migrations.AlterField(
            model_name='group',
            name='files',
            field=models.ManyToManyField(default=list, related_name='group_files', to='Users.files'),
        ),
    ]
