# Generated by Django 4.2.9 on 2024-11-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_number_of_group_per_supervisor', models.PositiveSmallIntegerField(default=8)),
                ('minimum_number_of_group_per_supervisor', models.PositiveSmallIntegerField(default=2)),
                ('proposal_deadline', models.DateField(blank=True, null=True)),
                ('pre_defence_deadline', models.DateField(blank=True, null=True)),
                ('defence_deadline', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('sort_weight', models.IntegerField(default=1000)),
            ],
        ),
    ]
