# Generated by Django 4.2.9 on 2024-11-01 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField()),
                ('related_file', models.FileField(upload_to='notices/')),
            ],
        ),
        migrations.CreateModel(
            name='Group_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='group_files/')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_files', to='Users.group')),
            ],
        ),
    ]
